/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sheet_8.Question_2;

import java.awt.*;

/**
 *
 * @author N&M
 */
public class Paint extends javax.swing.JFrame {
    int x1,x2,y1,y2;
    Color color;
    Graphics g;
    
    /**
     * Creates new form Paint
     */
    public Paint() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        BtnG1 = new javax.swing.ButtonGroup();
        red = new javax.swing.JRadioButton();
        blue = new javax.swing.JRadioButton();
        green = new javax.swing.JRadioButton();
        magenta = new javax.swing.JRadioButton();
        edged = new javax.swing.JCheckBox();
        filled = new javax.swing.JCheckBox();
        shape = new javax.swing.JComboBox<>();
        panel = new javax.swing.JPanel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        BtnG1.add(red);
        red.setText("RED");
        red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redActionPerformed(evt);
            }
        });

        BtnG1.add(blue);
        blue.setText("BLUE");

        BtnG1.add(green);
        green.setText("GREEN");

        BtnG1.add(magenta);
        magenta.setText("MAGENTA");

        edged.setText("Edges");

        filled.setText("Filled");

        shape.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "line", "circle", "square" }));
        shape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shapeActionPerformed(evt);
            }
        });

        panel.setBackground(new java.awt.Color(153, 153, 153));
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(edged)
                        .addGap(33, 33, 33)
                        .addComponent(filled)
                        .addGap(70, 70, 70)
                        .addComponent(shape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(red)
                        .addGap(28, 28, 28)
                        .addComponent(blue)
                        .addGap(33, 33, 33)
                        .addComponent(green)
                        .addGap(18, 18, 18)
                        .addComponent(magenta)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(red)
                    .addComponent(blue)
                    .addComponent(green)
                    .addComponent(magenta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edged)
                    .addComponent(filled)
                    .addComponent(shape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shapeActionPerformed

    private void panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseClicked
        // TODO add your handling code here:
        g = panel.getGraphics();
        x1 =evt.getX();
        y1=evt.getY();
        color = Color.RED;
        if(red.isSelected()) color = Color.RED;
        else if(blue.isSelected()) color = Color.BLUE;
        else if(green.isSelected()) color = Color.GREEN;
        else if(magenta.isSelected()) color = Color.MAGENTA;
        
        if(shape.getSelectedItem().equals("circle")){
            g.setColor(color);
            if(filled.isSelected()){
                g.drawOval(x1, y1, 100, 100);
                g.fillOval(x1, y1, 100, 100);
            }
            else
                g.drawOval(x1, y1, 100, 100);
        }
        if(shape.getSelectedItem().equals("square")){
            g.setColor(color);
            if(filled.isSelected()){
                g.drawRect(x1, y1, 100, 100);
                g.fillRect(x1, y1, 100, 100);
            }
            else
                g.drawRect(x1, y1, 100, 100);
        }
        
    }//GEN-LAST:event_panelMouseClicked

    private void redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redActionPerformed

    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        // TODO add your handling code here:
        x2=evt.getX();
        y2=evt.getY();
        if(shape.getSelectedItem().equals("line")){
            g.setColor(color);
            if(filled.isSelected()){
                g.drawLine(x1, y1, x2, y2);
            }
            else
                g.drawLine(x1, y1, x2, y2);
        }
    }//GEN-LAST:event_panelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnG1;
    private javax.swing.JRadioButton blue;
    private javax.swing.JCheckBox edged;
    private javax.swing.JCheckBox filled;
    private javax.swing.JRadioButton green;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton magenta;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButton red;
    private javax.swing.JComboBox<String> shape;
    // End of variables declaration//GEN-END:variables
}
